from engine import Engine

def test_out_of_board():
    engine = Engine(8, 12)
    assert(engine.is_on_board((8, 0)) == False)
    assert(engine.is_on_board((7, 0)) == True)
    assert(engine.is_on_board((0, 0)) == True)
    assert(engine.is_on_board((-1, 0)) == False)
    assert(engine.is_on_board((7, 11)) == True)
    assert(engine.is_on_board((7, 12)) == False)
    assert(engine.is_on_board((8, 11)) == False)
    assert(engine.is_on_board((8, 12)) == False)
    assert(engine.is_on_board((3, 12)) == False)
    assert(engine.is_on_board((3, -12)) == False)
    assert(engine.is_on_board((3, 10)) == True)

def test_out_of_board2():
    engine = Engine(3, 3)
    assert(engine.is_on_board((8, 0)) == False)
    assert(engine.is_on_board((7, 0)) == False)
    assert(engine.is_on_board((0, 0)) == True)
    assert(engine.is_on_board((-1, 0)) == False)
    assert(engine.is_on_board((7, 11)) == False)
    assert(engine.is_on_board((7, 12)) == False)
    assert(engine.is_on_board((8, 11)) == False)
    assert(engine.is_on_board((8, 12)) == False)
    assert(engine.is_on_board((3, 12)) == False)
    assert(engine.is_on_board((3, -12)) == False)
    assert(engine.is_on_board((3, 10)) == False)
    assert(engine.is_on_board((2, 2)) == True)
    assert(engine.is_on_board((3, 3)) == False)
    assert(engine.is_on_board((0, 3)) == False)
    assert(engine.is_on_board((3, 0)) == False)
    assert(engine.is_on_board((2, 0)) == True)
