from engine import Engine
from heuristics import HeuristicDemo
from move import Move
from human_player import HumanPlayer

def test_heuristic_value():
    engine = Engine()
    engine.execute(Move(False, 3, (0,0)))
    engine.execute(Move(False, 5, (0,1)))
    engine.execute(Move(False, 8, (2,0)))
    engine.execute(Move(False, 8, (3,0)))
    engine.execute(Move(False, 4, (2,2)))
    engine.execute(Move(False, 4, (3,2)))
    engine.execute(Move(False, 3, (4,0)))
    engine.execute(Move(False, 3, (4,1)))
    engine.execute(Move(False, 1, (4,2)))
    h = HeuristicDemo()
    assert(h.value(0, engine) == 12)

def test_heuristic_value_2():
    engine = Engine()
    engine.execute(Move(False, 3, (0,0)))
    engine.execute(Move(False, 5, (0,1)))
    engine.execute(Move(False, 2, (0,2)))
    engine.execute(Move(False, 8, (2,0)))
    engine.execute(Move(False, 8, (3,0)))
    engine.execute(Move(False, 4, (2,2)))
    engine.execute(Move(False, 4, (3,2)))
    engine.execute(Move(False, 3, (4,0)))
    engine.execute(Move(False, 1, (4,1)))
    h = HeuristicDemo()
    assert(h.value(0, engine) == -2)

def test_heuristic_value_3():
    engine = Engine()
    engine.execute(Move(False, 3, (0,0)))
    engine.execute(Move(False, 5, (0,1)))
    engine.execute(Move(False, 8, (2,0)))
    engine.execute(Move(False, 6, (3,0)))
    engine.execute(Move(False, 3, (4,0)))
    engine.execute(Move(False, 1, (4,1)))
    engine.execute(Move(False, 1, (4,2)))
    engine.execute(Move(False, 3, (6,0)))
    engine.execute(Move(False, 4, (6,1)))
    engine.execute(Move(False, 4, (7,1)))
    h = HeuristicDemo()
    assert(h.value(0, engine) == -27)

def test_heuristic_value_magic():
    engine = Engine(dark_magic=True)
    engine.execute(Move(False, 3, (0,0)))
    engine.execute(Move(False, 5, (0,1)))
    engine.execute(Move(False, 8, (2,0)))
    engine.execute(Move(False, 8, (3,0)))
    engine.execute(Move(False, 4, (2,2)))
    engine.execute(Move(False, 4, (3,2)))
    engine.execute(Move(False, 3, (4,0)))
    engine.execute(Move(False, 3, (4,1)))
    engine.execute(Move(False, 1, (4,2)))
    h = HeuristicDemo()
    assert(h.value(0, engine) == 12)

def test_heuristic_value_2_magic():
    engine = Engine(dark_magic=True)
    engine.execute(Move(False, 3, (0,0)))
    engine.execute(Move(False, 5, (0,1)))
    engine.execute(Move(False, 2, (0,2)))
    engine.execute(Move(False, 8, (2,0)))
    engine.execute(Move(False, 8, (3,0)))
    engine.execute(Move(False, 4, (2,2)))
    engine.execute(Move(False, 4, (3,2)))
    engine.execute(Move(False, 3, (4,0)))
    engine.execute(Move(False, 1, (4,1)))
    h = HeuristicDemo()
    assert(h.value(0, engine) == -2)

def test_heuristic_value_3_magic():
    engine = Engine(dark_magic=True)
    engine.execute(Move(False, 3, (0,0)))
    engine.execute(Move(False, 5, (0,1)))
    engine.execute(Move(False, 8, (2,0)))
    engine.execute(Move(False, 6, (3,0)))
    engine.execute(Move(False, 3, (4,0)))
    engine.execute(Move(False, 1, (4,1)))
    engine.execute(Move(False, 1, (4,2)))
    engine.execute(Move(False, 3, (6,0)))
    engine.execute(Move(False, 4, (6,1)))
    engine.execute(Move(False, 4, (7,1)))
    h = HeuristicDemo()
    assert(h.value(0, engine) == -27)
